writer:
  logdir: runs/atmosphere/opt/step_lr/all

run: optimizer

data:
  category: atmosphere
  dataConfigPath: datasets/atmosphere/data_config.yaml
  trainDatasets:
    - lz2_lxy256
    - lz2_lxy128
    - lz2_lxy64
    - lz2_lxy32
    - lz2_lxy16
  batchSize: 128

training:
  epochs: 6000
  eval_epochs: 100
  model:
    name: atmosphere
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 1250
    stepGamma: 0.5
