writer:
  logdir: runs/atmosphere/opt/cosine_annealing/lz2_lxy16

run: optimizer

data:
  category: atmosphere
  dataConfigPath: datasets/atmosphere/data_config.yaml
  trainDatasets:
    - lz2_lxy16
  batchSize: 128

training:
  epochs: 6000
  eval_epochs: 200
  model:
    name: atmosphere
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 1000
    TMult: 2
    etaMin: 0
    lastEpoch: -1
