writer:
  logdir: runs/dnn1/lz2_lxy256

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  lz: 2
  lxy: 256
  batchSize: 16
  trainSplit: 0.8

training:
  epochs: 20000
  eval_epochs: 100
  model:
    name: dnn1
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 5000
    stepGamma: 0.5
