writer:
  logdir: runs/cnn_dnn2/step_lr/lz2_lxy128

run: optimizer

data:
  dataConfigPath: datasets/data_config.yaml
  trainDatasets:
    - lz2_lxy128
  batchSize: 16

training:
  epochs: 12000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 3000
    stepGamma: 0.5
