writer:
  logdir: runs/cnn_dnn2/cosine_annealing/lz2_lxy64

run: optimizer

data:
  dataConfigPath: datasets/data_config.yaml
  trainDatasets:
    - lz2_lxy64
  batchSize: 16

training:
  epochs: 12000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 2000
    TMult: 2
    etaMin: 0
    lastEpoch: -1
