writer:
  logdir: runs/cnn_dnn2/cosine_annealing/lz2_lxy256

run: optimizer

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  trainDatasets:
    - lz2_lxy256
  batchSize: 8
  trainSplit: 0.8

training:
  epochs: 20000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 4000
    TMult: 2
    etaMin: 0
    lastEpoch: -1
