writer:
  logdir: runs/dnn1/lz2_lxy128

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  lz: 2
  lxy: 128
  batchSize: 32
  trainSplit: 0.8

training:
  epochs: 16000
  eval_epochs: 200
  model:
    name: dnn1
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 4000
    stepGamma: 0.5
