writer:
  logdir: runs/maml/cnn_dnn2_run3/b_256

run: maml

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  baseDatasets:
    - lz2_lxy256
  targetDatasets:
    - lz2_lxy128
    - lz2_lxy64
    - lz2_lxy32
    - lz2_lxy16
  batchSizeBase: 16
  batchSizeTarget: 128
  trainSplit: 0.8

training:
  epochs: 14000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  mamlLR: 0.0001
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 4000
    stepGamma: 0.5
