writer:
  logdir: runs/ocean/maml/from_pretrained/02

run: maml

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  baseDatasets:
    - lsel50
  targetDatasets:
    - lsel100
    - lsel200
    - lsel400
  batchSizeBase: 500
  mamlK: 30000

training:
  epochs: 40000
  eval_epochs: 10
  model:
    name: ocean
    stateDictPath: runs/ocean/opt/step_lr/lsel50/model.pt
  loss: mse
  mamlLR: 0.000001
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 50000
    stepGamma: 0.5

