writer:
  logdir: runs/debug

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel400
  batchSize: 64

training:
  epochs: 30
  eval_epochs: 10
  model:
    name: ocean
    stateDictPath:
    freezeChildren:
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 100
    stepGamma: 0.5
