writer:
  logdir: runs/debug_opt

run: optimizer

data:
  dataConfigPath: datasets/data_config.yaml
  trainDatasets:
    - lz2_lxy256
  batchSize: 64

training:
  epochs: 30
  eval_epochs: 10
  model:
    name: cnn_dnn2
    stateDictPath:
    freezeChildren:
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 100
    stepGamma: 0.5
