writer:
  logdir: runs/cnn_dnn2/leave_out/lz2_lxy64

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  trainDatasets:
    - lz2_lxy256
    - lz2_lxy128
    - lz2_lxy32
    - lz2_lxy16
  batchSize: 128
  trainSplit: 0.8

training:
  epochs: 5000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 1250
    stepGamma: 0.5
