writer:
  logdir: runs/lz1_lxy16

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  lz: 1
  lxy: 16
  batchSize: 16
  trainSplit: 0.8

training:
  epochs: 500
  eval_epochs: 4
  model:
    name: simple
  loss: mse
  optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
  lrScheduler:
    name: step
    stepStepSize: 100
    stepGamma: 0.5
