writer:
  logdir: runs/maml/cnn_dnn2_run6/01

run: maml

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  baseDatasets:
    - lz2_lxy256
  targetDatasets:
    - lz2_lxy16
    - lz2_lxy32
    - lz2_lxy64
    - lz2_lxy128
  batchSizeBase: 8
  trainSplit: 0.8

training:
  epochs: 20000
  eval_epochs: 50
  model:
    name: cnn_dnn2
    stateDictPath: runs/cnn_dnn2/cosine_annealing/lz2_lxy16/model.pt
  loss: mse
  mamlLR: 0.00001
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 2000
    stepGamma: 0.5
