writer:
  logdir: runs/cnn_dnn2/all

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  all: true
  batchSize: 128
  trainSplit: 0.8

training:
  epochs: 5000
  eval_epochs: 50
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 1250
    stepGamma: 0.5
