writer:
  logdir: runs/cnn_dnn2/lz2_lxy32

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  lz: 2
  lxy: 32
  batchSize: 64
  trainSplit: 0.8

training:
  epochs: 8000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 2000
    stepGamma: 0.5
