writer:
  logdir: runs/default

data:
  dataConfigPath: datasets/data_config.yaml
  trainDatasets:
    - lz2_lxy256
  batchSize: 4
  baseDatasets:
    - lz2_lxy256
    - lz2_lxy128
  targetDatasets:
    - lz2_lxy256
  mamlK: 256
  batchSizeBase: 64

run: optimizer

training:
  epochs: 2000
  eval_epochs: 50
  model:
    name: simple
  loss: mse
  optimizer:
    name: sgd
    lr: 0.0001
    momentum: 0.9
    weightDecay: 0.00001
  lrScheduler:
    name: step
    stepStepSize: 1000
    stepGamma: 0.5
