writer:
  logdir: runs/ocean/opt/step_lr/lsel50

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel50
  batchSize: 256

training:
  epochs: 30
  eval_epochs: 1
  model:
    name: ocean
  loss: mse
  optimizer:
    name: adam
    lr: 0.0001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 10
    stepGamma: 0.5