writer:
  logdir: runs/ocean/opt/step_lr/lsel200

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel200
  batchSize: 75600

training:
  epochs: 600
  eval_epochs: 10
  model:
    name: ocean
  loss: mse
  optimizer:
    name: adam
    lr: 0.01
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 200
    stepGamma: 0.5