writer:
  logdir: training/runs/default

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  lz: 1
  lxy: 256
  batchSize: 4
  trainSplit: 0.8

training:
  epochs: 10000
  eval_epochs: 200
  model:
    name: simple
  loss: mse
  optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
  lrScheduler:
    name: step
    stepStepSize: 2000
    stepGamma: 0.5

