writer:
  logdir: runs/maml/randomly_initialized/02

run: maml

data:
  dataConfigPath: datasets/data_config.yaml
  baseDatasets:
    - lz2_lxy16
    - lz2_lxy32
    - lz2_lxy64
    - lz2_lxy128
    - lz2_lxy256
  targetDatasets:
    - lz2_lxy16
    - lz2_lxy32
    - lz2_lxy64
    - lz2_lxy128
    - lz2_lxy256
  batchSizeBase: 512
  mamlK: 99999999999

training:
  epochs: 25000
  eval_epochs: 100
  model:
    name: cnn_dnn2
  loss: mse
  mamlLR: 0.000001
  optimizer:
    name: adam
    lr: 0.01
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 5000
    stepGamma: 0.5
