writer:
  logdir: runs/ocean/maml/randomly_initialized/03

run: maml

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  baseDatasets:
    - lsel50
    - lsel100
    - lsel200
    - lsel400
  targetDatasets:
    - lsel50
    - lsel100
    - lsel200
    - lsel400
  batchSizeBase: 5000
  mamlK: 3000000

training:
  epochs: 40000
  eval_epochs: 10
  model:
    name: ocean
  loss: mse
  mamlLR: 0.000001
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: step
    stepStepSize: 50000
    stepGamma: 0.5

