writer:
  logdir: runs/ocean/opt/cosine_annealing/all

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel50
    - lsel100
    - lsel200
    - lsel400
  batchSize: 75600

training:
  epochs: 300
  eval_epochs: 1
  model:
    name: ocean
  loss: mse
  optimizer:
    name: adam
    lr: 0.01
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 50
    TMult: 2
    etaMin: 0
    lastEpoch: -1
