writer:
  logdir: runs/ocean/opt/cosine_annealing/lsel50

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel50
  batchSize: 75600

training:
  epochs: 800
  eval_epochs: 5
  model:
    name: ocean
  loss: mse
  optimizer:
    name: adam
    lr: 0.01
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 100
    TMult: 2
    etaMin: 0
    lastEpoch: -1