writer:
  logdir: runs/ocean/opt/cosine_annealing/lsel50

run: optimizer

data:
  category: ocean
  dataConfigPath: datasets/ocean/data_config.yaml
  trainDatasets:
    - lsel50
  batchSize: 256

training:
  epochs: 1000
  eval_epochs: 5
  model:
    name: ocean
  loss: mse
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 1000
    TMult: 2
    etaMin: 0
    lastEpoch: -1