writer:
  logdir: runs/maml/cnn_dnn2_run5/b_16

run: maml

data:
  dataConfigPath: datasets/training_data/data_config.yaml
  baseDatasets:
    - lz2_lxy16
  targetDatasets:
    - lz2_lxy32
    - lz2_lxy64
    - lz2_lxy128
    - lz2_lxy256
  batchSizeBase: 128
  trainSplit: 0.8

training:
  epochs: 20000
  eval_epochs: 200
  model:
    name: cnn_dnn2
  loss: mse
  mamlLR: 0.00001
  optimizer:
    name: adam
    lr: 0.001
    betas: 0.9, 0.999
  lrScheduler:
    name: cosineAnnealingWarmRestarts
    T0: 2000
    TMult: 1
    etaMin: 0
    lastEpoch: -1
